dist: trusty

sudo: false

language: cpp

compiler: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
            - gcc-4.9
            - cmake
            - lcov
            - cppcheck
            - doxygen

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

before_script:
    - ./travis/before_script.sh

script:
    - ./travis/script.sh

after_script:
    - ./travis/after_script.sh

before_deploy:
    - doxygen Doxyfile

deploy:
    provider: pages
    skip_cleanup: true
    local_dir: docs/html
    github_token: $GH_REPO_TOKEN
    on:
        branch: master